name: Update EPG from Private Repo

on:
  schedule:
    - cron: '0 0 */2 * *' # setiap hari tengah malam, bisa disesuaikan
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Repo (this repo)
        uses: actions/checkout@v4

      - name: Checkout Private Repo (alkhalifitv.github.io)
        uses: actions/checkout@v4
        with:
          repository: alkhalifitv/alkhalifitv.github.io
          token: ${{ secrets.EPG_TOKEN }} 
          path: private-repo

      - name: Copy EPG file to epg folder
        run: |
          mkdir -p epg
          cp private-repo/guide/global/guide.xml.gz epg/

      - name: Commit and Push changes
        run: |
          git config user.name "alkhalifitv"
          git config user.email "backtrack512@gmail.com"
          git add epg/guide.xml.gz
          git commit -m "Update guide.xml.gz from private repo" --no-verify || echo "No changes to commit"
          git push origin master

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './epg'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
