name: Update and Deploy EPG every 2 days

on:
  schedule:
    # Cron setiap 2 hari sekali pukul 01:00 UTC (sesuaikan waktu kamu)
    - cron: '0 5 */2 * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo (this repo)
        uses: actions/checkout@v4

      - name: Checkout Private Repo (alkhalifitv.github.io)
        uses: actions/checkout@v4
        with:
          repository: alkhalifitv/alkhalifitv.github.io
          token: ${{ secrets.EPG_TOKEN }}
          path: private-repo

      - name: Prepare epg folder and copy EPG files
        run: |
          mkdir -p epg
          cp -v private-repo/guide/global/*.xml.gz epg/ || echo "No global XML files found"
          cp -v private-repo/guide/local/*.xml.gz epg/ || echo "No local XML files found"
          ls -lh epg

      - name: Commit and Push changes if any
        run: |
          git config user.name "alkhalifitv"
          git config user.email "backtrack512@gmail.com"
          git add epg/
          git commit -m "Update guide.xml.gz from private repo" --no-verify || echo "No changes to commit"
          git push origin master

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './epg'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
