name: Update dan Deploy EPG setiap 2 hari

on:
  schedule:
    - cron: '30 22 */2 * *'   # Jalan tiap 2 hari
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo (this repo)
        uses: actions/checkout@v4

      - name: Checkout private repo (alkhalifitv.github.io)
        uses: actions/checkout@v4
        with:
          repository: alkhalifitv/alkhalifitv.github.io
          token: ${{ secrets.EPG_TOKEN }}
          path: private-repo

      - name: Copy only idn.xml.gz and guide.xml.gz to epg folder
        run: |
          mkdir -p epg
          cp -v private-repo/guide/global/guide.xml.gz epg/ || echo "guide.xml.gz not found"
          cp -v private-repo/guide/global/idn.xml.gz epg/ || echo "idn.xml.gz not found"
          ls -lh epg

      - name: Commit and push changes if any
        run: |
          git config user.name "alkhalifitv"
          git config user.email "backtrack512@gmail.com"
          git add epg/
          git diff --cached --quiet || git commit -m "Update selected EPG files from private repo" --no-verify
          git push origin master

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './epg'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
